<table cellpadding=2 cellspacing=2>
<tr>
<td bgcolor=#cccccc width=150 align="center"><a href="?seite=a_emstime.php">Podsumowanie</a></td>
<!-- td bgcolor=#cccccc><a href="?seite=a_emsstat.php">Statystyka</a></td -->
<td bgcolor=#cccccc width=150 align="center"><a href="?seite=a_emshour.php">Ostatnia godzina</a></td>
<td bgcolor=#cccccc width=150 align="center"><a href="?seite=a_emsday.php">Dzisiaj</a></td>
<td bgcolor=#cccccc width=150 align="center"><a href="?seite=a_emshw.php">Ostatnie 3 dni</a></td>
<td bgcolor=#cccccc width=150 align="center"><a href="?seite=a_emsweek.php">Tydzień</a></td>
<td bgcolor=#cccccc width=150 align="center"><a href="?seite=a_emsmonth.php">Miesiąc</a></td></tr>
</table>